spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/alcohol_friday_local
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ON_SECRET
    password: ON_SECRET
  jpa:
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
custom:
  tossPayments:
    widget:
      clientKey: test_ck_yZqmkKeP8g9y6Z7oq0GdVbQRxB9l
      secretKey: ON_SECRET