spring:
  profiles:
    active: dev
    group:
      dev:
        - file
        - secret
logging:
  level:
    com.drunkenlion.alcoholfriday: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
springdoc:
  swagger-ui:
    path: /docs
