spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/alcohol_friday
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Chlehdcjf123!
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
