name: ci

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests
        run: ./gradlew test

      - name: Check test results
        uses: actions/github-script@v1
        with:
          script: |
            if (github.event.pull_request.head.sha !== github.sha) {
              throw new Error('The pull request head SHA does not match the workflow run SHA.')
            }

            const testResults = await getTestResults()
            if (!testResults.success) {
              throw new Error('The tests failed.')
            }

            console.log('The tests passed.')
