name: ci

on:
  pull_request:
    branches:
      - dev

jobs:
 test:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v3
        
      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew test

      - name: Check test results
        uses: actions/github-script@v1
        with:
          script: |
            if (github.event.pull_request.head.sha !== github.sha) {
              throw new Error('The pull request head SHA does not match the workflow run SHA.')
            }

            const testResults = await getTestResults()
            if (!testResults.success) {
              throw new Error('The tests failed.')
            }

            console.log('The tests passed.')
